### ISSUE TITLE
Arrows in the cartesian product disappear 

### ISSUE THREAD

**Issue by edumapurunga** [fsmMLK/inkscapeCartesianStemPlot#3]
When adding a second stem plot the arrows of the first added one disappear.
This also happens if I add a third stem plot, in that case, the arrows of  the second Cartesian product also disappear. 
In fact, only the last added stem plot has the arrows in the axis. 
The problem vanishes when inkscape is restarted.

Screenshot of the problem. 
![image](https://user-images.githubusercontent.com/24210620/111873276-50352480-896e-11eb-97f6-ccce6b10320e.png)

System Setup:

```
System:    Kernel: 5.4.0-67-generic x86_64 bits: 64 compiler: gcc v: 9.3.0 Desktop: Cinnamon 4.6.7 
           wm: muffin dm: LightDM Distro: Linux Mint 20 Ulyana base: Ubuntu 20.04 focal  

Graphics:  Device-1: Intel UHD Graphics 630 vendor: Acer Incorporated ALI driver: i915 v: kernel 
           bus ID: 00:02.0 chip ID: 8086:3e9b 
           Device-2: NVIDIA GP107M [GeForce GTX 1050 Ti Mobile] vendor: Acer Incorporated ALI 
           driver: nvidia v: 450.102.04 bus ID: 01:00.0 chip ID: 10de:1c8c 
           Display: x11 server: X.Org 1.20.9 driver: modesetting,nvidia 
           unloaded: fbdev,nouveau,vesa resolution: 1920x1080~60Hz 
           OpenGL: renderer: Mesa Intel UHD Graphics 630 (CFL GT2) v: 4.6 Mesa 20.2.6 
           direct render: Yes 
```

Inkscape version: `1.0.2 (1.0.2+r75+1)`

**Comment by fsmMLK** [comment]
Unfortunately this is an Inkscape issue. I noticed that in recent versions.

**Comment by edumapurunga** [comment]
Do you have any idea of what may be causing this behavior?
